alquilando/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('contract/', include('contract.urls')),
    path('admin/', admin.site.urls),
]

contract/urls.py
from django.urls import path

from . import views

app_name = 'contract'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

contract/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

contract/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from django.forms import ModelForm

class NameForm(forms.Form):
	your_name = forms.CharField(label='Your name', max_length=100, required=False)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class ProfileForm(forms.Form):

    # Propietarios 
    nombre_propietario1 = forms.CharField(label='Nombre Completo de Propietario/a/s', max_length=250, required=False)
    dni_propietario1 = forms.CharField(label='DNI de pripietario', max_length=250, required=False)
    dirrecion_propietario1 = forms.CharField(label='Dirección del propietario', max_length=250, required=False)

    nombre_propietario2 = forms.CharField(label='Nombre Completo de Propietario/a/s', max_length=250, required=False)
    dni_propietario2 = forms.CharField(label='DNI de pripietario', max_length=250, required=False)
    dirrecion_propietario2 = forms.CharField(label='Dirección del propietario', max_length=250, required=False)

    nombre_propietario3 = forms.CharField(label='Nombre Completo de Propietario/a/s', max_length=250, required=False)
    dni_propietario3 = forms.CharField(label='DNI de pripietario', max_length=250, required=False)
    dirrecion_propietario3 = forms.CharField(label='Dirección del propietario', max_length=250, required=False)

    nombre_propietario4 = forms.CharField(label='Nombre Completo de Propietario/a/s', max_length=250, required=False)
    dni_propietario4 = forms.CharField(label='DNI de pripietario', max_length=250, required=False)
    dirrecion_propietario4 = forms.CharField(label='Dirección del propietario', max_length=250, required=False)

    nombre_propietario5 = forms.CharField(label='Nombre Completo de Propietario/a/s', max_length=250, required=False)
    dni_propietario5 = forms.CharField(label='DNI de pripietario', max_length=250, required=False)
    dirrecion_propietario5 = forms.CharField(label='Dirección del propietario', max_length=250, required=False)

    # Inquilinos
    nombre_inquilino1 = forms.CharField(label='Nombre Completo de Inquilino/a/s', max_length=250, required=False)
    tipo_documento1 = forms.CharField(label='Tipo del Documento', max_length=250, required=False)
    numero_documento1 = forms.CharField(label='Número del documento', max_length=250, required=False)
    dirrecion_inquilino1 = forms.CharField(label='Dirreción de inquilino', max_length=250, required=False)

    nombre_inquilino2 = forms.CharField(label='Nombre Completo de Inquilino/a/s', max_length=250, required=False)
    tipo_documento2 = forms.CharField(label='Tipo del Documento', max_length=250, required=False)
    numero_documento2 = forms.CharField(label='Número del documento', max_length=250, required=False)
    dirrecion_inquilino2 = forms.CharField(label='Dirreción de inquilino', max_length=250, required=False)

    nombre_inquilino3 = forms.CharField(label='Nombre Completo de Inquilino/a/s', max_length=250, required=False)
    tipo_documento3 = forms.CharField(label='Tipo del Documento', max_length=250, required=False)
    numero_documento3 = forms.CharField(label='Número del documento', max_length=250, required=False)
    dirrecion_inquilino3 = forms.CharField(label='Dirreción de inquilino', max_length=250, required=False)

    nombre_inquilino4 = forms.CharField(label='Nombre Completo de Inquilino/a/s', max_length=250, required=False)
    tipo_documento4 = forms.CharField(label='Tipo del Documento', max_length=250, required=False)
    numero_documento4 = forms.CharField(label='Número del documento', max_length=250, required=False)
    dirrecion_inquilino4 = forms.CharField(label='Dirreción de inquilino', max_length=250, required=False)

    # Other info

    calle = forms.CharField(label='Dirección completa del departamento a Alquiler', max_length=250, required=False)
    fecha_comienzo = forms.DateField(label='Fecha comienzo contrato', widget = forms.SelectDateWidget, required=True)
    fecha_ingreso = forms.DateField(label='Fecha de ingreso (si no hay proporcional, deja vacío)', widget = forms.SelectDateWidget, required=False)
    num_props = forms.IntegerField(label='Número de Propietarios', required=False)
    num_inq = forms.IntegerField(label='Número de Inquilinos', required=False)
    
    
    texto_monto = forms.CharField(label='Mostrar en texto monto del contrato', max_length=250, required=False)
    valor_monto = forms.CharField(label='Mostrar valor del contrato', max_length=250, required=False)

    perct = '%'
    alquiler = forms.FloatField(label='Valor de Alquiler', required=False)
    ajuste = forms.FloatField(label='Ajuste (12.50{} sería 12.50)'.format(perct), required=False)
    semestral_o_anual = forms.BooleanField(label='Si SEMESTRAL, marca esta casilla. Si ANUAL, dejalo vacío.', required=False)

    nombre_garante = forms.CharField(label='Nombre de garante: si eligiste 1 arriba', max_length=250, required=False)
    matricula = forms.CharField(label='Matrícula FR (.../..): si eligiste 1 arriba', max_length=250, required=False)
    numero_poliza = forms.CharField(label='Número de póliza: si eligiste 2-5 arriba', max_length=250, required=False)
    nombre_finaer = forms.CharField(label='Nombre de representante de Finaer: si eligiste 6 arriba', max_length=250, required=False)
    documento_representanto = forms.CharField(label='Número de documento representante: si eligiste 6 arriba', max_length=250, required=False)

    numero_monto_deposito = forms.FloatField(label='Mostrar monto en número del depósito', required=False)

    option1 = forms.BooleanField(label='1) Garantía Propietaria', required=False)
    option2 = forms.BooleanField(label='2) SMG Compañía Argentina de Seguros SA', required=False)
    option3 = forms.BooleanField(label='3) Fianzas y Crédito S.A. Cia. De Seguros', required=False)
    option4 = forms.BooleanField(label='4) Aseguradora PROVINCIA SEGUROS S.A.', required=False)
    option5 = forms.BooleanField(label='5) Alba Caución Compañía Argentina de Seguros', required=False)
    option6 = forms.BooleanField(label='6) Sistema Finaer S.A.', required=False)

contract/templates/contract/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'contract:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

contract/templates/contract/index.html
<!-- FORM FOR PROFILE INFORMATION -->

	<form action='/contract/' target='_self' method='post'>
	<div class = "cell large-9 medium-9 small-8">
	{% csrf_token %}
	<table class="unstriped">

		<thead> <!-- CONTACT INFORMATION -->
			<tr style="background-color:rgba(255, 0, 0, 0.2)">
				<th width="200" style="background-color:rgba(255, 0, 0, 0.2)">Los Propietarios</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Primero Propietario</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Segundo Propietario</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Tercero Propietario</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Cuarto Propietario</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Quinto Propietario</th>
			</tr>
		</thead>
		<tbody>
		
			<tr>
				<td>{{ form.nombre_propietario1.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_propietario1.errors }}
					{{ form.nombre_propietario1 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_propietario2.errors }}
					{{ form.nombre_propietario2 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_propietario3.errors }}
					{{ form.nombre_propietario3 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_propietario4.errors }}
					{{ form.nombre_propietario4 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_propietario5.errors }}
					{{ form.nombre_propietario5 }}
				</div></td>
			</tr>

			<tr>
				<td>{{ form.dni_propietario1.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.dni_propietario1.errors }}
					{{ form.dni_propietario1 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.dni_propietario2.errors }}
					{{ form.dni_propietario2 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.dni_propietario3.errors }}
					{{ form.dni_propietario3 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.dni_propietario4.errors }}
					{{ form.dni_propietario4 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.dni_propietario5.errors }}
					{{ form.dni_propietario5 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.dirrecion_propietario1.label }}</td>
				<td><div class="cell large-6">
					{{ form.dirrecion_propietario1.errors }}
					{{ form.dirrecion_propietario1 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.dirrecion_propietario2.errors }}
					{{ form.dirrecion_propietario2 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.dirrecion_propietario3.errors }}
					{{ form.dirrecion_propietario3 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.dirrecion_propietario4.errors }}
					{{ form.dirrecion_propietario4 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.dirrecion_propietario5.errors }}
					{{ form.dirrecion_propietario5 }}
				</div></td>
			</tr>
			<thead> <!-- DATE INFORMATION -->
				<tr style="background-color:rgba(255, 0, 0, 0.2)">
					<th width="200" style="background-color:rgba(255, 0, 0, 0.2)">Los Inquilinos</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Primero Inquilino</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Segundo Inquilino</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Tercero Inquilino</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)">Cuarto Inquilino</th>
				</tr>
			</thead>

			<tr>
				<td>{{ form.nombre_inquilino1.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_inquilino1.errors }}
					{{ form.nombre_inquilino1 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_inquilino2.errors }}
					{{ form.nombre_inquilino2 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_inquilino3.errors }}
					{{ form.nombre_inquilino3 }}
				</div></td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_inquilino4.errors }}
					{{ form.nombre_inquilino4 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.tipo_documento1.label }}</td>
				<td><div class="cell large-6">
					{{ form.tipo_documento1.errors }}
					{{ form.tipo_documento1 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.tipo_documento2.errors }}
					{{ form.tipo_documento2 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.tipo_documento3.errors }}
					{{ form.tipo_documento3 }}
				</div></td>
				<td><div class="cell large-6">
					{{ form.tipo_documento4.errors }}
					{{ form.tipo_documento4 }}
				</div></td>
			</tr>
			<tr>
					<td>{{ form.numero_documento1.label }}</td>
					<td><div class="cell large-6">
						{{ form.numero_documento1.errors }}
						{{ form.numero_documento1 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.numero_documento2.errors }}
						{{ form.numero_documento2 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.numero_documento3.errors }}
						{{ form.numero_documento3 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.numero_documento4.errors }}
						{{ form.numero_documento4 }}
					</div></td>
				</tr>
			<tr>

			<tr>
					<td>{{ form.dirrecion_inquilino1.label }}</td>
					<td><div class="cell large-6">
						{{ form.dirrecion_inquilino1.errors }}
						{{ form.dirrecion_inquilino1 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.dirrecion_inquilino2.errors }}
						{{ form.dirrecion_inquilino2 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.dirrecion_inquilino3.errors }}
						{{ form.dirrecion_inquilino3 }}
					</div></td>
					<td><div class="cell large-6">
						{{ form.dirrecion_inquilino4.errors }}
						{{ form.dirrecion_inquilino4 }}
					</div></td>
				</tr>

			<thead> <!-- DATE INFORMATION -->
				<tr style="background-color:rgba(255, 0, 0, 0.2)">
					<th width="200" style="background-color:rgba(255, 0, 0, 0.2)">El Contrato</th>
					<th style="background-color:rgba(255, 0, 0, 0.2)"></th>
				</tr>
			</thead>

			<tr>
				<td>{{ form.alquiler.label }}</td>
				<td><div class="cell large-6">
					{{ form.alquiler.errors }}
					{{ form.alquiler }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.ajuste.label }}</td>
				<td><div class="cell large-6">
					{{ form.ajuste.errors }}
					{{ form.ajuste }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.semestral_o_anual.label }}</td>
				<td><div class="cell large-6">
					{{ form.semestral_o_anual.errors }}
					{{ form.semestral_o_anual }}
				</div></td>
			</tr>
				<td>{{ form.calle.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.calle.errors }}
					{{ form.calle }}
				</div></td>
			</tr>	

			<tr>
				<td>{{ form.fecha_comienzo.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.fecha_comienzo.errors }}
					{{ form.fecha_comienzo }}
				</div></td>
			</tr>

			<tr>
				<td>{{ form.fecha_ingreso.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.fecha_ingreso.errors }}
					{{ form.fecha_ingreso }}
				</div></td>
			</tr>

			<tr>
				<td>{{ form.numero_monto_deposito.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.numero_monto_deposito.errors }}
					{{ form.numero_monto_deposito }}
				</div></td>
			</tr>

		<thead> <!-- OPTION INFORMATION -->
			<tr style="background-color:rgba(255, 0, 0, 0.2)">
				<th width="200" style="background-color:rgba(255, 0, 0, 0.2)">Elija solo UNO de los siguientes.</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)"></th>
			</tr>
		</thead>

			<tr>
				<td>{{ form.option1.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option1.errors }}
					{{ form.option1 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.option2.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option2.errors }}
					{{ form.option2 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.option3.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option3.errors }}
					{{ form.option3 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.option4.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option4.errors }}
					{{ form.option4 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.option5.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option5.errors }}
					{{ form.option5 }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.option6.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.option6.errors }}
					{{ form.option6 }}
				</div></td>
			</tr>
		</tbody> <!-- END OF CONTACT INFORMATION -->

		<thead> <!-- OPTION INFORMATION -->
			<tr style="background-color:rgba(255, 0, 0, 0.2)">
				<th width="200" style="background-color:rgba(255, 0, 0, 0.2)">Optional Information</th>
				<th style="background-color:rgba(255, 0, 0, 0.2)"></th>
			</tr>
		</thead>

			<tr>
				<td>{{ form.nombre_garante.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_garante.errors }}
					{{ form.nombre_garante }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.matricula.label }}</td>
				<td><div class="cell large-6">
					{{ form.matricula.errors }}
					{{ form.matricula }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.numero_poliza.label }}</td>
				<td><div class="cell large-6">
					{{ form.numero_poliza.errors }}
					{{ form.numero_poliza }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.nombre_finaer.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.nombre_finaer.errors }}
					{{ form.nombre_finaer }}
				</div></td>
			</tr>
			<tr>
				<td>{{ form.documento_representanto.label }}</td>
				<td><div class="fieldWrapper cell large-6">
					{{ form.documento_representanto.errors }}
					{{ form.documento_representanto }}
				</div></td>
			</tr>

		<thead> <!-- BUTTONS -->
			<tr>
				<form action="PHP.php" id="test" method="post">
     			</form>
				<td><input type="submit" class="button small" value="Create Contract"></td>		
			</tr>
		</thead> <!-- END OF BUTTONS -->

	</table>
	</form> <!-- END OF FORM FOR PROFILE INFORMATION -->

	</div>
	</table>
	</form> <!-- END OF FORM FOR PROFILE INFORMATION -->
</body>
</html>

contract/templates/contract/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'contract:detail' question.id %}">Vote again?</a>